using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CentralSolutions.Migrations
{
    /// <inheritdoc />
    public partial class AddDepartments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "departments",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    IsActive = table.Column<bool>(type: "INTEGER", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_departments", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_departments_Name",
                table: "departments",
                column: "Name",
                unique: true);

            migrationBuilder.Sql("""
                INSERT INTO departments (Name, IsActive, CreatedAt) VALUES
                ('10° DIP', 1, CURRENT_TIMESTAMP),
                ('11º DIP', 1, CURRENT_TIMESTAMP),
                ('12° DIP', 1, CURRENT_TIMESTAMP),
                ('13º DIP', 1, CURRENT_TIMESTAMP),
                ('14º DIP', 1, CURRENT_TIMESTAMP),
                ('15º DIP', 1, CURRENT_TIMESTAMP),
                ('16º DIP', 1, CURRENT_TIMESTAMP),
                ('17º DIP', 1, CURRENT_TIMESTAMP),
                ('18º DIP', 1, CURRENT_TIMESTAMP),
                ('197-DIPC', 1, CURRENT_TIMESTAMP),
                ('19º DIP', 1, CURRENT_TIMESTAMP),
                ('1º DIP', 1, CURRENT_TIMESTAMP),
                ('20º DIP', 1, CURRENT_TIMESTAMP),
                ('21º DIP', 1, CURRENT_TIMESTAMP),
                ('22º DIP', 1, CURRENT_TIMESTAMP),
                ('23º DIP', 1, CURRENT_TIMESTAMP),
                ('24º DIP', 1, CURRENT_TIMESTAMP),
                ('25º DIP', 1, CURRENT_TIMESTAMP),
                ('26º DIP', 1, CURRENT_TIMESTAMP),
                ('27º DIP', 1, CURRENT_TIMESTAMP),
                ('28º DIP', 1, CURRENT_TIMESTAMP),
                ('29º DIP', 1, CURRENT_TIMESTAMP),
                ('2º DIP', 1, CURRENT_TIMESTAMP),
                ('30° DIP', 1, CURRENT_TIMESTAMP),
                ('31ª DIP', 1, CURRENT_TIMESTAMP),
                ('32º DIP', 1, CURRENT_TIMESTAMP),
                ('33ª DIP', 1, CURRENT_TIMESTAMP),
                ('34ª DIP', 1, CURRENT_TIMESTAMP),
                ('35ª DIP', 1, CURRENT_TIMESTAMP),
                ('36º DIP', 1, CURRENT_TIMESTAMP),
                ('37º DIP', 1, CURRENT_TIMESTAMP),
                ('38° DIP', 1, CURRENT_TIMESTAMP),
                ('39ª DIP', 1, CURRENT_TIMESTAMP),
                ('3º DIP', 1, CURRENT_TIMESTAMP),
                ('40ª DIP', 1, CURRENT_TIMESTAMP),
                ('41ª DIP', 1, CURRENT_TIMESTAMP),
                ('42ª DIP', 1, CURRENT_TIMESTAMP),
                ('43ª DIP', 1, CURRENT_TIMESTAMP),
                ('44ª DIP', 1, CURRENT_TIMESTAMP),
                ('45ª DIP', 1, CURRENT_TIMESTAMP),
                ('46ª DIP', 1, CURRENT_TIMESTAMP),
                ('47ª DIP', 1, CURRENT_TIMESTAMP),
                ('48ª DIP', 1, CURRENT_TIMESTAMP),
                ('49ª DIP', 1, CURRENT_TIMESTAMP),
                ('4º DIP', 1, CURRENT_TIMESTAMP),
                ('50ª DIP', 1, CURRENT_TIMESTAMP),
                ('51ª DIP', 1, CURRENT_TIMESTAMP),
                ('52ª DIP', 1, CURRENT_TIMESTAMP),
                ('53ª DIP', 1, CURRENT_TIMESTAMP),
                ('54º DIP', 1, CURRENT_TIMESTAMP),
                ('55º DIP', 1, CURRENT_TIMESTAMP),
                ('56ª DIP', 1, CURRENT_TIMESTAMP),
                ('57ª DIP', 1, CURRENT_TIMESTAMP),
                ('58ª DIP', 1, CURRENT_TIMESTAMP),
                ('59ª DIP', 1, CURRENT_TIMESTAMP),
                ('5º DIP', 1, CURRENT_TIMESTAMP),
                ('60ª DIP', 1, CURRENT_TIMESTAMP),
                ('61ª DIP', 1, CURRENT_TIMESTAMP),
                ('62ª DIP', 1, CURRENT_TIMESTAMP),
                ('63ª DIP', 1, CURRENT_TIMESTAMP),
                ('64ª DIP', 1, CURRENT_TIMESTAMP),
                ('65ª DIP', 1, CURRENT_TIMESTAMP),
                ('66ª DIP', 1, CURRENT_TIMESTAMP),
                ('67ª DIP', 1, CURRENT_TIMESTAMP),
                ('68ª DIP', 1, CURRENT_TIMESTAMP),
                ('69ª DIP', 1, CURRENT_TIMESTAMP),
                ('6º DIP', 1, CURRENT_TIMESTAMP),
                ('70º DIP', 1, CURRENT_TIMESTAMP),
                ('71º DIP', 1, CURRENT_TIMESTAMP),
                ('72ª DIP', 1, CURRENT_TIMESTAMP),
                ('73ª DIP', 1, CURRENT_TIMESTAMP),
                ('74º DIP', 1, CURRENT_TIMESTAMP),
                ('75ª DIP', 1, CURRENT_TIMESTAMP),
                ('76ª DIP/PCAM', 1, CURRENT_TIMESTAMP),
                ('77ª DIP', 1, CURRENT_TIMESTAMP),
                ('78° DIP', 1, CURRENT_TIMESTAMP),
                ('79ª DIP', 1, CURRENT_TIMESTAMP),
                ('7º DIP', 1, CURRENT_TIMESTAMP),
                ('80º DIP', 1, CURRENT_TIMESTAMP),
                ('81ª DIP', 1, CURRENT_TIMESTAMP),
                ('8º DIP', 1, CURRENT_TIMESTAMP),
                ('9º DIP', 1, CURRENT_TIMESTAMP),
                ('ApoioGab', 1, CURRENT_TIMESTAMP),
                ('Arq/DG BIC', 1, CURRENT_TIMESTAMP),
                ('AsseImpre/PC', 1, CURRENT_TIMESTAMP),
                ('AsseJur/PC', 1, CURRENT_TIMESTAMP),
                ('BV', 1, CURRENT_TIMESTAMP),
                ('CAF/PC', 1, CURRENT_TIMESTAMP),
                ('CCTD/PC', 1, CURRENT_TIMESTAMP),
                ('CECPPC/2021', 1, CURRENT_TIMESTAMP),
                ('CEMC', 1, CURRENT_TIMESTAMP),
                ('CEPCAM-2022', 1, CURRENT_TIMESTAMP),
                ('CI-DIPC', 1, CURRENT_TIMESTAMP),
                ('CI-PCAM', 1, CURRENT_TIMESTAMP),
                ('Ciberlab-DIP', 1, CURRENT_TIMESTAMP),
                ('CIEX', 1, CURRENT_TIMESTAMP),
                ('Cobra/DPI', 1, CURRENT_TIMESTAMP),
                ('COR/DPI', 1, CURRENT_TIMESTAMP),
                ('CORE', 1, CURRENT_TIMESTAMP),
                ('CP/CAF', 1, CURRENT_TIMESTAMP),
                ('CP/DPI', 1, CURRENT_TIMESTAMP),
                ('CPPF/PC', 1, CURRENT_TIMESTAMP),
                ('CURSO', 1, CURRENT_TIMESTAMP),
                ('CVA', 1, CURRENT_TIMESTAMP),
                ('CVTR', 1, CURRENT_TIMESTAMP),
                ('DAF', 1, CURRENT_TIMESTAMP),
                ('DCA', 1, CURRENT_TIMESTAMP),
                ('DEAAI', 1, CURRENT_TIMESTAMP),
                ('DEAT', 1, CURRENT_TIMESTAMP),
                ('DECCFPE', 1, CURRENT_TIMESTAMP),
                ('DECCI', 1, CURRENT_TIMESTAMP),
                ('DECCM - N/L', 1, CURRENT_TIMESTAMP),
                ('DECCM - O/S', 1, CURRENT_TIMESTAMP),
                ('DECCM/PLV', 1, CURRENT_TIMESTAMP),
                ('DECCOR', 1, CURRENT_TIMESTAMP),
                ('DECCT', 1, CURRENT_TIMESTAMP),
                ('DECON', 1, CURRENT_TIMESTAMP),
                ('DECP', 1, CURRENT_TIMESTAMP),
                ('DEFLU', 1, CURRENT_TIMESTAMP),
                ('DEGMF', 1, CURRENT_TIMESTAMP),
                ('DEHS', 1, CURRENT_TIMESTAMP),
                ('DEHS ZonaZer', 1, CURRENT_TIMESTAMP),
                ('DEHS-ANEXO', 1, CURRENT_TIMESTAMP),
                ('DEHS-REQ', 1, CURRENT_TIMESTAMP),
                ('DEHS/LESTE', 1, CURRENT_TIMESTAMP),
                ('DEHS/NORTE', 1, CURRENT_TIMESTAMP),
                ('DEHS/OESTE', 1, CURRENT_TIMESTAMP),
                ('DEHS/SUL', 1, CURRENT_TIMESTAMP),
                ('DEMA', 1, CURRENT_TIMESTAMP),
                ('DENARC', 1, CURRENT_TIMESTAMP),
                ('DEOPS', 1, CURRENT_TIMESTAMP),
                ('DEP/Coari', 1, CURRENT_TIMESTAMP),
                ('DEP/Eirunepé', 1, CURRENT_TIMESTAMP),
                ('DEP/HUMAITÁ', 1, CURRENT_TIMESTAMP),
                ('DEP/Itacoati', 1, CURRENT_TIMESTAMP),
                ('DEP/Labrea', 1, CURRENT_TIMESTAMP),
                ('DEP/Manacapu', 1, CURRENT_TIMESTAMP),
                ('DEP/Parintin', 1, CURRENT_TIMESTAMP),
                ('DEP/Tabating', 1, CURRENT_TIMESTAMP),
                ('DEP/Tefé', 1, CURRENT_TIMESTAMP),
                ('DEPCA', 1, CURRENT_TIMESTAMP),
                ('DEPCA/BXDOS', 1, CURRENT_TIMESTAMP),
                ('DEPCA/FUGA', 1, CURRENT_TIMESTAMP),
                ('DEPCA/REPREC', 1, CURRENT_TIMESTAMP),
                ('DEPLAN', 1, CURRENT_TIMESTAMP),
                ('DERCC', 1, CURRENT_TIMESTAMP),
                ('DERCC/Privad', 1, CURRENT_TIMESTAMP),
                ('DERFD', 1, CURRENT_TIMESTAMP),
                ('DERFD/Priva', 1, CURRENT_TIMESTAMP),
                ('DERFDlatro', 1, CURRENT_TIMESTAMP),
                ('DERFDprecato', 1, CURRENT_TIMESTAMP),
                ('DERFDrepre', 1, CURRENT_TIMESTAMP),
                ('DERFV', 1, CURRENT_TIMESTAMP),
                ('DERFV/Privad', 1, CURRENT_TIMESTAMP),
                ('DEV/DRAD', 1, CURRENT_TIMESTAMP),
                ('DIP - SGC', 1, CURRENT_TIMESTAMP),
                ('DIP Eirunepé', 1, CURRENT_TIMESTAMP),
                ('DIP HUMAITÁ', 1, CURRENT_TIMESTAMP),
                ('DIP Manacapu', 1, CURRENT_TIMESTAMP),
                ('DIP/Coari', 1, CURRENT_TIMESTAMP),
                ('DIP/Itacoati', 1, CURRENT_TIMESTAMP),
                ('DIP/Labrea', 1, CURRENT_TIMESTAMP),
                ('DIP/Parintin', 1, CURRENT_TIMESTAMP),
                ('DIP/Tefe', 1, CURRENT_TIMESTAMP),
                ('DIPC-PCAM', 1, CURRENT_TIMESTAMP),
                ('DIPTabatinga', 1, CURRENT_TIMESTAMP),
                ('DIVERSOS', 1, CURRENT_TIMESTAMP),
                ('DPI', 1, CURRENT_TIMESTAMP),
                ('DPI-FREQUENC', 1, CURRENT_TIMESTAMP),
                ('DPM', 1, CURRENT_TIMESTAMP),
                ('DRAD', 1, CURRENT_TIMESTAMP),
                ('DRCO', 1, CURRENT_TIMESTAMP),
                ('DRCO/PRIVADO', 1, CURRENT_TIMESTAMP),
                ('DTI', 1, CURRENT_TIMESTAMP),
                ('E-Sic/E-Ouv', 1, CURRENT_TIMESTAMP),
                ('GA/DAF', 1, CURRENT_TIMESTAMP),
                ('GAO/DPM', 1, CURRENT_TIMESTAMP),
                ('GDG', 1, CURRENT_TIMESTAMP),
                ('GDGA', 1, CURRENT_TIMESTAMP),
                ('GE/Drad', 1, CURRENT_TIMESTAMP),
                ('GECOM', 1, CURRENT_TIMESTAMP),
                ('GerAlmox/DAF', 1, CURRENT_TIMESTAMP),
                ('GerArm/DAF', 1, CURRENT_TIMESTAMP),
                ('GerComp/DAF', 1, CURRENT_TIMESTAMP),
                ('GerCont/DAF', 1, CURRENT_TIMESTAMP),
                ('GerEng/DAF', 1, CURRENT_TIMESTAMP),
                ('GerPat/DAF', 1, CURRENT_TIMESTAMP),
                ('GETRAN', 1, CURRENT_TIMESTAMP),
                ('GGP', 1, CURRENT_TIMESTAMP),
                ('GID', 1, CURRENT_TIMESTAMP),
                ('GMF/DAF', 1, CURRENT_TIMESTAMP),
                ('GOA/PC', 1, CURRENT_TIMESTAMP),
                ('Gofin/DAF', 1, CURRENT_TIMESTAMP),
                ('GP/DAF', 1, CURRENT_TIMESTAMP),
                ('GPD/DAF', 1, CURRENT_TIMESTAMP),
                ('GRIPJ', 1, CURRENT_TIMESTAMP),
                ('GUP/DPM', 1, CURRENT_TIMESTAMP),
                ('NECRIM/PCAM', 1, CURRENT_TIMESTAMP),
                ('NIPED/PCAM', 1, CURRENT_TIMESTAMP),
                ('NIRC/PCAM', 1, CURRENT_TIMESTAMP),
                ('NOMEAR', 1, CURRENT_TIMESTAMP),
                ('NOT/DPI', 1, CURRENT_TIMESTAMP),
                ('Notificações', 1, CURRENT_TIMESTAMP),
                ('NURATI/PCAM', 1, CURRENT_TIMESTAMP),
                ('NURRC', 1, CURRENT_TIMESTAMP),
                ('ORGANOGRAMA', 1, CURRENT_TIMESTAMP),
                ('OS/DPI', 1, CURRENT_TIMESTAMP),
                ('PDI/PCAM', 1, CURRENT_TIMESTAMP),
                ('PG flsdpagam', 1, CURRENT_TIMESTAMP),
                ('PI- DG', 1, CURRENT_TIMESTAMP),
                ('Plantão DEHS', 1, CURRENT_TIMESTAMP),
                ('PPI Cacau', 1, CURRENT_TIMESTAMP),
                ('PPI CaVarzea', 1, CURRENT_TIMESTAMP),
                ('PPI Matupi', 1, CURRENT_TIMESTAMP),
                ('PRDGD', 1, CURRENT_TIMESTAMP),
                ('PRECAT-DERCC', 1, CURRENT_TIMESTAMP),
                ('PRO-VIDA', 1, CURRENT_TIMESTAMP),
                ('Protocolo DG', 1, CURRENT_TIMESTAMP),
                ('PSICOSSOCIAL', 1, CURRENT_TIMESTAMP),
                ('RECABRI', 1, CURRENT_TIMESTAMP),
                ('SETORINATIVO', 1, CURRENT_TIMESTAMP),
                ('UAIP/PC', 1, CURRENT_TIMESTAMP);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "departments");
        }
    }
}
